site_name: p2p-copy
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Module Layout: layout.md
  - API: api.md
  - APIExamples: examples.md
  - Relay Setup: relay.md
  - Features: features.md
  - Security: security.md
  - Troubleshooting: troubleshooting.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true        # show the object's name as a heading
            show_root_full_path: true      # show the full path
            show_signature: true           # include the call signature
            separate_signature: true       # put signature in its own code block
            docstring_style: numpy
            members_order: source
  - search

repo_url: https://github.com/AfuLD/p2p-copy