site_name: p2p-copy
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API: api.md
  - Module Layout: layout.md
  - Relay Setup: relay.md
  - Features: features.md
  - Security: security.md
  - Troubleshooting: troubleshooting.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature_annotations: true
            members_order: source
  - search

repo_url: https://github.com/AfuLD/p2p-copy